### ISSUE TITLE
Add table of contents to all articles and only display them on mobile/print

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [se-edu/learningresources#138]
# Progress:
- [X] Update Contribution Guide to reflect need for content page (PR #181)

- [X] Programming Languages
  - [X] C++
    - [X] Rvalue References and Move Semantics (PR #144)
  - [X] CSharp
	- [X] Introduction to CSharp (PR #144)
  - [X] Go (PR #144)
  - [X] Haskell (PR #144)
  - [x] Java
    - [x] Java Concurrency (PR #150)
    - [x] Java Streams (PR #150)
    - [x] Java Synchronization (PR #150)
    - [x] Java Reflection (PR #150)
    - [x] JUnit (PR #150)
  - [X] JavaScript
    - [X] Writing Testable JavaScript Code (PR #153)
    - [X] Javascript Promises (PR #153)
    - [X] Javascript Modules (PR #153)
    - [X] Static Typing in JavaScript (PR #153)
  - [X] Kotlin
    - [X] Introduction to Kotlin (PR #153)
    - [X] Null Safety In Kotlin (PR #153)
  - [X] Python (PR #154)
  - [X] Ruby (PR #154)
  - [X] Rust (PR #154)
  - [X] Scala (PR #154)
  - [X] Swift (PR #154)

- [X] SE Topics
  - [X] Architecture
    - [X] REST (PR #155)
  - [X] Code Quality
    - [X] Code Quality Metrics (PR #155)
  - [X] Documentation (PR #155)
  - [X] Functional Programming (PR #155)
  - [X] Performance
    - [X] Introduction to Performance Optimization (PR #155)
    - [X] Performance Profiling (PR #155)
    - [X] Web Performance (PR #155)
  - [X] Project Management
    - [X] Agile Development (PR #155)
    - [X] DevOps (PR #155)
  - [X] Revision Control
    - [X] Best Practices with git (PR #155)
  - [X] Scalability (PR #155)
  - [X] Static Analysis
    - [X] Introduction to Static Analysis (PR #176)
    - [X] CheckStyle (PR #176)
    - [X] PMD (PR #176)
    - [X] FindBugs (PR #176)
    - [X] ESLint (PR #176)
  - [X] Testing
    - [X] Integration Testing (PR #176)
    - [X] Writing Testable Code (PR #176)
  - [X] UI/UX
    - [X] Accessibility (PR #176)
    - [X] Design Systems (PR #176)
    - [X] Introduction to UI/UX (PR #176)
    - [X] Refining UX Design Skills (PR #176)

- [X] App Frameworks
  - [X] Android (#177)
  - [X] Angular (#177)
  - [X] iOS (#177)
  - [X] Node (#177)
  - [X] React (#177)
  - [X] Ruby on Rails (#177)
  - [X] Vue (#177)

- [X] Tools Useful for Software Engineers
  - [X] Regular Expressions (#178)
  - [X] Docker (#178)

- [X] Other Topics
  - [X] Computer Vision (#178)
  - [X] Databases
    - [X] DBMS (#178)
    - [X] SQL (#178)
  - [X] Machine Learning (#178)
  - [X] Multi-Threading
    - [X] GPGPU (#178)
    - [X] CUDA (#178)
  - [X] Security
    - [X] Cross Site Request Forgery (#180)
    - [X] Cross Site Scripting (#180)
    - [X] Cryptography (#180)
    - [X] HTTPS (#180)
    - [X] Password Storage (#180)
    - [X] SQL Injection (#180)
  - [X] Shell
    - [X] bash (#180)

# Chapters Added in 19/20
- [X] (#168) NumPy (Already added by author. Pending Broken Link Fix: #179)

---

# Initial Discussion (concluded):
11 / 45 topics currently have a table of contents. I personally find that the table of contents adds unnecessary clutter as there is already a navigation sidebar to the right that serves the same purpose.

This is especially prominent on the [CUDA](https://se-education.org/learningresources/contents/gpgpu/cuda.html) page, where the table of contents occupies the whole initial screen:

![image](https://user-images.githubusercontent.com/43085796/74106918-e90f4300-4ba5-11ea-926a-5255b9f62eb2.png)

I propose that the 11 topics have their table of contents removed and the contribution guidelines updated to reflect this as well.

This is the CUDA page, with table of contents removed:

![image](https://user-images.githubusercontent.com/43085796/74107024-efea8580-4ba6-11ea-85d4-a41008309eaf.png)

Much cleaner and less overwhelming in my opinion.

What are your thoughts?

**Comment by damithc** [comment]
I have no objections. A ToC is useful for printing and for converting to PDF though.

**Comment by iskandarzulkarnaien** [comment]
Alright, thanks Prof!

@xantho09 @openorclose @ccyccyccy @madanalogy @yash-chowdhary 

Could I get your opinion on this? Remove or no?

**Comment by madanalogy** [comment]
Personally prefer a third option of simplifying content pages that are deemed too long, reason being that **the nav bar is not available on mobile screens**. I feel like it would be good to have some form of enhanced navigability (i.e. TOC) for mobile users, but you're right in that some of them are too fine in their segregation of content.

**Comment by openorclose** [comment]
How about putting the TOC in all articles, then display it only for printing or on mobile, but hide it if the screen shows the nav sidebars

**Comment by madanalogy** [comment]
> How about putting the TOC in all articles, then display it only for printing or on mobile, but hide it if the screen shows the nav sidebars

That sound cleaner if it's possible, I like this idea (Y)

**Comment by iskandarzulkarnaien** [comment]
Thanks for the responses guys! Great ideas all around.

So it seems this is the direction I'll be taking:
1) Update all articles with a TOC
2) Only show TOC for mobile/print view

I'm also thinking of creating and including a link to a sample 'skeleton' with the appropriate formatting
in the contributing section, so future contributors won't have to dig around to find the correct formatting to use for their TOCs.

Thanks again!

**Comment by damithc** [comment]
> So it seems this is the direction I'll be taking:
> 
> 1. Update all articles with a TOC
> 2. Only show TOC for mobile/print view

One downside is problems with the ToC  could go unnoticed by authors and PR reiewers as the ToC will not show up in the Netlify preview.

**Comment by iskandarzulkarnaien** [comment]
> One downside is problems with the ToC could go unnoticed by authors and PR reiewers as the ToC will not show up in the Netlify preview.

PR reviewers can use Chrome/Firefox devtools to test out the mobile view, plus they can test out the print preview to see if everything is good to go.

The main problem in my opinion is that this change requires slightly more meticulousness from reviewers and authors to also test mobile and print views. This is not difficult to do but it is an additional step that cannot be missed.

I am thinking of updating the contribution guide to reflect this requirement.

Also [here](https://deploy-preview-142--learningresources.netlify.com/contents/revisioncontrol/bestpracticesgit) is a preview of the `Best Practices with git` article with the changes I have proposed.

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

**Comment by Tejas2805** [comment]
@iskandarzulkarnaien Can update this.
